version: '3'
services:
  upload_file_python:
    build: .
    image: upload_file_python
    container_name: upload_file_python 
    ports:
      - 4555:4555
    volumes:
      - ./src/files:/app/src/files
